services:
  - type: web
    name: project-vorex
    env: python
    pythonVersion: "3.12"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
