services:
  - type: web
    name: project-vorex-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: UPDATE_WEBHOOK_URL
        sync: false
      - key: NODE_VERSION
        value: 20.16.0
      - key: UPDATE_TEST_ON_BOOT
        value: true
